### PR TITLE
Update readme description

### PR DESCRIPTION
**Pull request by rvdpas**

### CODE REVIEW

**Comment by wooorm** [comment]
Late, but 🎉

**Comment by rvdpas** [comment]
Readme assignment's deadline is 4-10 at 7 am, so it's not late?

**Comment by wooorm** [comment]
ohhh, no you’re fine in that case :)

**Comment by wooorm** [comment]
Wait no, because you just handed in your play assignment!

**Comment by rvdpas** [comment]
Oh, well that's my mistake. I just made a pull request and I guess it took all the changes? Any advice on how to do this with other assignments?

**Comment by wooorm** [comment]
Say you have our repo forked, and you branch from your master branch to assignment branches, your master brach will always be clean.

Then, when done with an assignment, go back to our repo and click "New pull request", setting the base repo to out repo, base branch to our master, head fork to your repo, and head branch to your corresponding assignment branch!

**Pull request merged**
