### PR TITLE
Add @floortje93

### PR DESCRIPTION
**Pull request by floortje93**

### CODE REVIEW

**Comment by wooorm** [comment]
Nice, but how is this a bar chart? 🤔

**Comment by floortje93** [comment]
Oh thats right.. i just picked a nice looking graph in the 'basic' graph section. I'll redo the assignment tomorrowmorning (2/10) if thats okay.

**Comment by wooorm** [comment]
No problem, it’s fine! You‘re the second person to do this, so [I made it more clear](https://github.com/cmda-fe3/course-17-18/blob/master/class-1.md#description).

**Comment by wooorm** [comment]
Oh and you took our site down by uploading files in `site/class-1-bar/` instead of site/class-1-bar/floortje93! Hacker you!

**Pull request merged**
