### PR TITLE
Add @laurens-booij

### PR DESCRIPTION
**Pull request by Laurens-booij**

### CODE REVIEW

**Comment by Laurens-booij** [comment]
I changed the data to 24 hours instead of one day. 

But I am clueless as to why huibergat shows up as undefined. It should be read just like the others I would think. Could you give me a nod in the right direction?

**Comment by wooorm** [comment]
It’s supposed to be empty, that’s why we chose it :p

**Comment by wooorm** [comment]
And your `index.txt` still shows multiple days?

**Comment by wooorm** [comment]
Ohhh, but you’re still drawing some part of it I guess? 🤔 That’s why it shows up in the left-top?

**Comment by Laurens-booij** [comment]
I think so.. I'll try to fix it

**Comment by Laurens-booij** [comment]
When I remove `if (d[7] === ""){return;}` from the map function I get back 5(?) array's. One for each town and one undefined. Where could this undefined array come from?

**Comment by wooorm** [comment]
No clue! 🤔

**Comment by Laurens-booij** [comment]
I just got it working when you merged it. Is there a possibility to change it still?

**Comment by wooorm** [comment]
Sure, by PRing your new files!

**Comment by wooorm** [comment]
So from your master create a branch `update-clean` or something, and add your files to the correct directory. Then, when I merge just the changes will be applied here!

**Pull request merged**
