### PR TITLE
Add @maaikvc

### PR DESCRIPTION
**Pull request by maaikevc**

### CODE REVIEW

**Comment by wooorm** [comment]
@maaikevc didn’t you already add your submission for the load assignment in GH-124?

**Comment by maaikevc** [comment]
I was trying to hand in my very cool bar chart, mmm, I’ll give it another try :-/

Op 2 okt. 2017, om 22:45 heeft Titus <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


@maaikevc<https://github.com/maaikevc> didn’t you already add your submission for the load assignment in GH-124<https://github.com/cmda-fe3/course-17-18/pull/124>?

**Comment by wooorm** [comment]
Hmm 🤔 Maybe remove this branch and try again? This time using `site/class-1-bar`?

**Comment by maaikevc** [comment]
ik dacht dat ik m nu wel goed had gepuld maar de Continuous Integration vindt het maar niks…

Op 2 okt. 2017, om 23:04 heeft Titus <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Hmm 🤔 Maybe remove this branch and try again? This time using site/class-1-bar?

**Comment by wooorm** [comment]
Gedoe 😛

Try again, and do let a lecturer know if you need help!

**Pull request closed without merging**
